# Generated by Django 2.2.6 on 2019-11-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('B', 'Bestseller'), ('E', '')], default='P', max_length=1),
        ),
    ]
